version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Build completed!"
artifacts:
  files:
    - '**/*'
